import { execFileSync } from 'node:child_process';
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const dbPath = resolve(root, 'content/site.sqlite');
const outputPath = resolve(root, 'src/lib/generated/content.js');

function query(sql) {
  const output = execFileSync('sqlite3', ['-json', dbPath, sql], {
    cwd: root,
    encoding: 'utf8'
  });

  return JSON.parse(output || '[]');
}

function lines(value) {
  return String(value)
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter(Boolean);
}

const postRows = query(`
  SELECT slug, category, title, date, summary, body
  FROM study_posts
  ORDER BY date DESC, category ASC, position ASC, slug ASC;
`);

const tagRows = query(`
  SELECT category, post_slug AS slug, tag
  FROM study_post_tags
  ORDER BY category ASC, post_slug ASC, position ASC, tag ASC;
`);

const projectRows = query(`
  SELECT slug, title, period, role, summary
  FROM projects
  ORDER BY slug ASC;
`);

const stackRows = query(`
  SELECT project_slug AS slug, item
  FROM project_stack
  ORDER BY project_slug ASC, position ASC, item ASC;
`);

const highlightRows = query(`
  SELECT project_slug AS slug, item
  FROM project_highlights
  ORDER BY project_slug ASC, position ASC, item ASC;
`);

function groupRows(rows, keyFn) {
  const groups = new Map();

  for (const row of rows) {
    const key = keyFn(row);
    const group = groups.get(key) ?? [];
    group.push(row);
    groups.set(key, group);
  }

  return groups;
}

const tagsByPost = groupRows(tagRows, (row) => `${row.category}/${row.slug}`);
const stackByProject = groupRows(stackRows, (row) => row.slug);
const highlightsByProject = groupRows(highlightRows, (row) => row.slug);

const studyPosts = postRows.map((post) => ({
  slug: post.slug,
  category: post.category,
  title: post.title,
  date: post.date,
  tags: (tagsByPost.get(`${post.category}/${post.slug}`) ?? []).map((row) => row.tag),
  summary: post.summary,
  body: lines(post.body)
}));

const projectItems = projectRows.map((project) => ({
  slug: project.slug,
  title: project.title,
  period: project.period,
  role: project.role,
  stack: (stackByProject.get(project.slug) ?? []).map((row) => row.item),
  summary: project.summary,
  highlights: (highlightsByProject.get(project.slug) ?? []).map((row) => row.item)
}));

const source = `// Generated by scripts/generate-content.mjs. Do not edit by hand.

export const studyPosts = ${JSON.stringify(studyPosts, null, 2)};

export const projectItems = ${JSON.stringify(projectItems, null, 2)};
`;

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, source);
